### ISSUE TITLE
Two errors found in this app.

### ISSUE THREAD

**Issue by Koreantuna29** [TechieBlossom/training_diet_app#2]
First it cannot run or build itself since the code standardEasing does not work and seonc there is no pubspec.yaml file found. Please help me fix this issue.

**Comment by TechieBlossom** [comment]
![Screenshot_20210110-171412_Chrome](https://user-images.githubusercontent.com/39679158/104121849-75525900-5367-11eb-8c05-c687049ffd21.jpg)
Please have a look at this screenshot.

Pubspec is there.
